### ISSUE TITLE
Optimize reset

### ISSUE THREAD

**Issue by hsalway1** [vuvuong003/CampusJobReview#12]
The reset filter button takes a long time to re render the original job reviews list.

Need to optimize it so that the jobs are displayed instantly.

**Comment by hsalway1** [comment]
This issue has been resolved in https://github.com/vuvuong003/CampusJobReview/pull/13. @vuvuong003 , could you please check if the working is as expected?

**Comment by vuvuong003** [comment]
It works!

**Comment by hsalway1** [comment]
Great! Closing the issue now.
