### ISSUE TITLE
Work on failing tests and badges

### ISSUE THREAD

**Issue by hsalway1** [vuvuong003/CampusJobReview#18]
Some tests are still failing and some code formatters have given multiple corrections to make.

**Comment by hsalway1** [comment]
Worked on this in https://github.com/vuvuong003/CampusJobReview/pull/19. Code coverage badge still needs to be fixed. @vuvuong003, you will have to work on this as you are the admin and need to link the repository to codecov.

**Comment by vuvuong003** [comment]
i have added the code coverage badge.
