### ISSUE TITLE
Discussion Board Feature

### ISSUE THREAD

**Issue by vuvuong003** [vuvuong003/CampusJobReview#2]
Implement a discussion board feature which let users comment on job reviews posted by other users, allowing them to ask question, provide advice or simply chat about the job that the user reviewed on

**Comment by vuvuong003** [comment]
@hsalway1 please review if the feature is functioning as expected on your end.

**Comment by hsalway1** [comment]
What PR deals with this issue? I need to review the changes.

**Comment by vuvuong003** [comment]
https://github.com/vuvuong003/CampusJobReview/pull/11

**Comment by hsalway1** [comment]
The PR looks good and I have verified the changes. You can close the issue!
