### ISSUE TITLE
Restrict the deletion of comments to the commenter only.

### ISSUE THREAD

**Issue by hsalway1** [vuvuong003/CampusJobReview#20]
At present, any user can delete any comment. We need to enforce a rule that only the original commenter can delete their own comment.

**Comment by hsalway1** [comment]
I have worked on this in https://github.com/vuvuong003/CampusJobReview/pull/21. @vuvuong003 can you check if the working is as expected? Thanks.

**Comment by vuvuong003** [comment]
Yeah, it works

**Comment by hsalway1** [comment]
Great. Closing the issue now.
