### ISSUE TITLE
Write tests for new enhancements

### ISSUE THREAD

**Issue by vuvuong003** [vuvuong003/CampusJobReview#3]

**Comment by vuvuong003** [comment]
I have written 6 tests on the frontend to test the functionality of the discussion board feature. Please continue to work on writing your tests!

**Comment by hsalway1** [comment]
I am almost done with the tests. You can expect a PR soon.

**Comment by Rohan0212** [comment]
I have also written 6 tests for the frontend to test the email verification and Profile section functionality. I am almost done with my backend tests.

**Comment by Rohan0212** [comment]
I have completed writing tests on the frontend and backend for the email verification and profile section functionalities.

**Comment by hsalway1** [comment]
I am done with adding tests. I have merged https://github.com/vuvuong003/CampusJobReview/pull/16 and https://github.com/vuvuong003/CampusJobReview/pull/17 into the test branch.

**Comment by hsalway1** [comment]
All the tests seem to be added for the added features. Closing this issue now.
