### ISSUE TITLE
Optimize Review Filters

### ISSUE THREAD

**Issue by hsalway1** [vuvuong003/CampusJobReview#4]
Currently filtering the job reviews is not very responsive. It takes 3-4 seconds to render the filtered list on the screen. 

## Steps to reproduce the issue:
- Log into the application
- Go to the 'View Reviews' section.
- Try applying the filters and click on 'Filter' button. 

## What is expected
- The list should be filtered instantly after clicking the filter button.

**Comment by hsalway1** [comment]
Pull request https://github.com/vuvuong003/CampusJobReview/pull/5 deals with this issue. @Rohan0212, could you test the changes?

**Comment by Rohan0212** [comment]
Looks good to me. Great Job!

**Comment by hsalway1** [comment]
Thanks. Closing this issue now.
