### ISSUE TITLE
Forget Password

### ISSUE THREAD

**Issue by vuvuong003** [vuvuong003/CampusJobReview#8]
Allow users to regain access to their password if they forget their original one.

**Comment by hsalway1** [comment]
I have worked on this issue in https://github.com/vuvuong003/CampusJobReview/pull/9. @vuvuong003, could you please test the changes? Thanks.

**Comment by vuvuong003** [comment]
Yeah, everything works.

**Comment by hsalway1** [comment]
Thanks, I am closing the issue.
